### ISSUE TITLE
Why does the slice function is colored in orange?

### ISSUE THREAD

**Issue by oasaleh** [Railly/one-hunter-vscode#55]
This is Python. The `slice` method has the same signature as `map` but has a different color. Also, I noticed a function named `reduce` will also have a different color. Is there a reason behind this behavior?

<img width="431" alt="image" src="https://github.com/Railly/one-hunter-vscode/assets/56449814/7955ed8d-9a03-4759-b10c-1fa78977b5c3">

**Comment by Railly** [comment]
Hey, thanks for reporting it. I'll be fixing several issues next week, including reducing the extension size😄

As for the `slice` color, I noticed the TextMate scope is different for each, causing them to inherit the same color as data types.

| `map` | `slice`|
| --- | ----- |
| ![image](https://github.com/Railly/one-hunter-vscode/assets/51397083/b1fc210f-a373-4b99-b410-9052a42ac9a1) | ![image](https://github.com/Railly/one-hunter-vscode/assets/51397083/545df896-a47a-44a0-9186-71b643ec2dd5) |

Could be fixed by reducing the specificity, so I'll give a try.

**Comment by Railly** [comment]
Should be fixed now!
